# Generated by Django 2.2.17 on 2021-01-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poseidon',
            name='count',
            field=models.IntegerField(verbose_name='Quantidade que será mostrada'),
        ),
        migrations.AlterField(
            model_name='poseidon',
            name='height',
            field=models.IntegerField(default=480, verbose_name='Altura (px)'),
        ),
        migrations.AlterField(
            model_name='poseidon',
            name='max_characters',
            field=models.IntegerField(verbose_name='Máximo de caracteres do texto'),
        ),
        migrations.AlterField(
            model_name='poseidon',
            name='needImage',
            field=models.BooleanField(verbose_name='Precisa ter imagem para aparecer na lista?'),
        ),
        migrations.AlterField(
            model_name='poseidon',
            name='pages',
            field=models.CharField(choices=[('portal_cms/slides.html', 'Slides'), ('portal_cms/teaching_graduation.html', 'Ensino - Graduação'), ('portal_cms/teaching_post.html', 'Ensino - Pós-graduação'), ('portal_cms/teaching_extension.html', 'Ensino - Extensão'), ('portal_cms/publications_dissertations.html', 'Publicações - Teses'), ('portal_cms/publications_thesis.html', 'Publicações - Dissertações'), ('portal_cms/laboratories.html', 'Laboratórios'), ('portal_cms/research.html', 'Pesquisa & Desenvolvimento'), ('portal_cms/team_member.html', 'Membro do Time')], max_length=50, verbose_name='Páginas a listar'),
        ),
        migrations.AlterField(
            model_name='poseidon',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='poseidon',
            name='type',
            field=models.CharField(choices=[('grid', 'Grade'), ('columns', 'Coluna'), ('horizontal', 'Horizontal'), ('vertical', 'Vertical')], max_length=50, verbose_name='Tipo de lista'),
        ),
        migrations.AlterField(
            model_name='poseidon',
            name='width',
            field=models.IntegerField(default=640, verbose_name='Largura (px)'),
        ),
    ]
