# Generated by Django 2.2.17 on 2021-01-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_cms', '0004_auto_20210108_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='poseidon',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição deve conter (deixar em branco para não filtrar):'),
        ),
    ]
