# Generated by Django 2.2.17 on 2021-01-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_cms', '0005_poseidon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poseidon',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subtipo (deixar em branco para não filtrar):'),
        ),
        migrations.AlterField(
            model_name='poseidon',
            name='pages',
            field=models.CharField(choices=[('portal_cms/slides.html', 'Slides'), ('portal_cms/teaching.html', 'Ensino'), ('portal_cms/publications_dissertations.html', 'Publicações - Teses'), ('portal_cms/publications_thesis.html', 'Publicações - Dissertações'), ('portal_cms/laboratories.html', 'Laboratórios'), ('portal_cms/research.html', 'Pesquisa & Desenvolvimento'), ('portal_cms/team_member.html', 'Membro do Time')], max_length=50, verbose_name='Páginas a listar'),
        ),
    ]
