# Generated by Django 2.2.17 on 2021-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_cms', '0006_auto_20210108_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('url', models.CharField(max_length=50, verbose_name='Link')),
                ('image', models.ImageField(upload_to='', verbose_name='Logo')),
            ],
        ),
        migrations.AlterField(
            model_name='poseidon',
            name='pages',
            field=models.CharField(choices=[('portal_cms/slides.html', 'Slides'), ('portal_cms/teaching.html', 'Ensino'), ('portal_cms/publications.html', 'Publicações'), ('portal_cms/publications_dissertations.html', 'Publicações - Teses'), ('portal_cms/publications_thesis.html', 'Publicações - Dissertações'), ('portal_cms/laboratories.html', 'Laboratórios'), ('portal_cms/research.html', 'Pesquisa & Desenvolvimento'), ('portal_cms/team_member.html', 'Membro do Time')], max_length=50, verbose_name='Páginas a listar'),
        ),
    ]
