# Generated by Django 2.2.17 on 2021-01-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_cms', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='poseidon',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Conteúdo descritivo'),
        ),
    ]
